### ISSUE TITLE
Drag Style Background Color

### ISSUE THREAD

**Issue by boomgetchopped** [STRML/react-grid-layout#1209]
Hello,

Great library!  The latest release is very stable and works exactly how we want. 

While dragging it shows a pink tile in the background.

How can I change the color?  Normally I would just do this in external css but It's hard to inspect the element in browser because it only shows up while dragging.

Thanks!

**Comment by josesaranda** [comment]
[Here](https://github.com/STRML/react-grid-layout/blob/master/css/styles.css)

```css
.react-grid-item.react-grid-placeholder {
  background: red;
  opacity: 0.2;
  transition-duration: 100ms;
  z-index: 2;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  -o-user-select: none;
  user-select: none;
}
```
These lines describe how element is styled. Rewrite them.
