### ISSUE TITLE
Clicking a grid item causes that item to drop far below my mouse pointer

### ISSUE THREAD

**Issue by Sawtaytoes** [STRML/react-grid-layout#171]
**react-grid-layout** 0.10.8.

For whatever reason, when I click a grid item, it shows the item I'm clicking 2-3 grid items below where my mouse pointer is. As soon as I start dragging, I see both the one I'm holding onto below my pointer and one where my mouse pointer is located (without any contents). Also, animations aren't working so I'm confused what's really going on here.

Is there a way to adjust it so this works like on the example pages?

```jsx
import React, { Component } from 'react'
import { renderToString } from 'react-dom/server'
import { connect } from 'react-redux'
import ReactGridLayout, {Responsive, WidthProvider} from 'react-grid-layout'
const ResponsiveReactGridLayout = WidthProvider(ReactGridLayout.Responsive)

// Utilities
import { stylesHelper } from 'utilities/styles-helper'

// Styles
const styles = [
	require('styl/stats')
]

class Stats extends Component {
	render() { return (
		<article>
			<section className="bubble">
				<ResponsiveReactGridLayout className="layout"
					breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
					cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}>
					<div key={"1"}>1</div>
					<div key={"2"}>2</div>
					<div key={"3"}>3</div>
				</ResponsiveReactGridLayout>
			</section>
		</article>
	)}
}

module.exports = connect(
	state => ({ playthroughs: state.playthroughs.playthroughs })
)(stylesHelper(Stats, styles))
```

**Comment by menelike** [comment]
does this happen on dragging or resizing as well?

**Comment by Sawtaytoes** [comment]
I don't have a resize handle showing up so I can't check. Is there a stylesheet I'm supposed to load in?

**Comment by menelike** [comment]
Taken from https://github.com/STRML/react-grid-layout/blob/master/css/styles.css this should add the handle to your component.

```css
.react-grid-item > .react-resizable-handle {
  position: absolute;
  width: 20px;
  height: 20px;
  bottom: 0;
  right: 0;
  background: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/Pg08IS0tIEdlbmVyYXRvcjogQWRvYmUgRmlyZXdvcmtzIENTNiwgRXhwb3J0IFNWRyBFeHRlbnNpb24gYnkgQWFyb24gQmVhbGwgKGh0dHA6Ly9maXJld29ya3MuYWJlYWxsLmNvbSkgLiBWZXJzaW9uOiAwLjYuMSAgLS0+DTwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DTxzdmcgaWQ9IlVudGl0bGVkLVBhZ2UlMjAxIiB2aWV3Qm94PSIwIDAgNiA2IiBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjojZmZmZmZmMDAiIHZlcnNpb249IjEuMSINCXhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHhtbDpzcGFjZT0icHJlc2VydmUiDQl4PSIwcHgiIHk9IjBweCIgd2lkdGg9IjZweCIgaGVpZ2h0PSI2cHgiDT4NCTxnIG9wYWNpdHk9IjAuMzAyIj4NCQk8cGF0aCBkPSJNIDYgNiBMIDAgNiBMIDAgNC4yIEwgNCA0LjIgTCA0LjIgNC4yIEwgNC4yIDAgTCA2IDAgTCA2IDYgTCA2IDYgWiIgZmlsbD0iIzAwMDAwMCIvPg0JPC9nPg08L3N2Zz4=');
  background-position: bottom right;
  padding: 0 3px 3px 0;
  background-repeat: no-repeat;
  background-origin: content-box;
  box-sizing: border-box;
  cursor: se-resize;
}
```
