### ISSUE TITLE
show and hide resize icon on hover?

### ISSUE THREAD

**Issue by varandpez** [STRML/react-grid-layout#213]
I know that in `react-resizable` I need to add class box3 to make the icon visible only on mouse over, how can I accomplish this in `react-grid-layout`? Thanks...

**Comment by STRML** [comment]
You can do this with any CSS - just set the handle to `display:none` by default and make it re-appear on grid hover.

**Comment by ejubkadric94** [comment]
This does not work. It breaks the resize functionality. Since the cursor "runs away" from the parent div while resizing, the whole resizing becomes laggy if you handle it with display: none like @STRML suggested.

The other way is to set the resize handle opacity to 0, and make it 1 on hover, but this is also a bit problematic. It appears and dissappears while resizing.

**Comment by STRML** [comment]
You're right that `display: none` is not the way to go. I've edited the comment to avoid others having this issue.

Generally, this pattern will work just fine:

```css
.react-grid-item > .react-resizable-handle {
  position: absolute;
  width: 20px;
  height: 20px;
  opacity: 0;
}

.react-grid-item:hover > .react-resizable-handle {
  opacity: 1;
}
```

It is possible that the handle disappears while dragging it if the page is heavy. You can address this with an animation or simply ignore it, as the mouse will occlude the handle anyway.
