### ISSUE TITLE
change to how margins work

### ISSUE THREAD

**Issue by jeffshaver** [STRML/react-grid-layout#324]
When you have one item in a row, it still gets margins for the left/right sides even though its the only  item and left/right gutters are only needed when there are multiple items in the row.

Even with multiple items in a row, i would imagine that the left-most item wouldn't need left margin and the right-most item wouldn't need right margin. This creates an un-removable grid-padding for the entire grid along the perimeter.

I would like the option to have margins only apply to space between items and not when its on the perimeter.

**Comment by STRML** [comment]
You can work around this by simply setting a negative margin on the container equal to the grid item margin.

The margin around the grid itself is intended. Since removing it can be trivially worked around with CSS, I'm going to close. Thanks for the report.

**Comment by jeffshaver** [comment]
@STRML from what i can tell, you can fix the left offset by setting a negative left margin on `.react-grid-layout` but you can't fix the extra space you now have on the right side

**Comment by STRML** [comment]
Try something like:

```css
  $gridMargin: 15px;
  .gridLayout {
    margin-top: -$gridMargin;
    margin-left: -$gridMargin;
    margin-right: -$gridMargin;
    width: calc(100% + ($gridMargin * -2)); // evens it out
  }
```
