### ISSUE TITLE
draggableCancel not working? - [Question]

### ISSUE THREAD

**Issue by zaraustra** [STRML/react-grid-layout#548]
Hi all,
I'm trying to add a simple div in absolute position with class "dragCancel".
My data-grid contains the flag " draggableCancel: '.dragCancel' ".
Now if I try to drag the element it doesn't care at all where I grab it, the "undraggable" area is not doing its work... How to solve it? 
HTML
```Javascript
 <ReactGridLayout className="layout" cols={1} rowHeight={35} width={500}>
    <div className="well" key="1" data-grid={{x: 0, y: 0, w: 1, h: 2, isResizable: false, draggableCancel: '.dragCancel'}}>
        It should drag from here..
        <div className="dragCancel">...but it should not from here...</div>
    </div>
</ReactGridLayout>
```
CSS
```css
  .dragCancel {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100px;
    height: 30px;
    background-color: green;
  }
```
