### ISSUE TITLE
Printing is page breaking in the middle of grid items (cutting them in half)

### ISSUE THREAD

**Issue by hickeroar** [STRML/react-grid-layout#589]
- [X] Bug
- [ ] Feature Request
- [x] Question

I'm trying to print a grid view, but I can't seem to get page breaks working properly. The printed pages are cutting rows of grid items in half horizontally instead of breaking before/after rows of them. I've tried various page break css settings on the react-grid-item divs, but nothing seems to be working. 

Is there a way to get this to work properly? Am I missing something obvious? Is it even possible?

**Comment by STRML** [comment]
Hi Ryan,

I don't have any plans to support this kind of styling. You may be able
to get there if you are creative with item and container heights/widths.

Ryan Vennell wrote:

**Comment by hickeroar** [comment]
OK Thanks. I ended up having to work toward re-inventing the grid view stuff for printing, though that may not end up working out. Thanks for the reply.

**Comment by Gervwyk** [comment]
Where you able to achieve this? I'm also trying to print a grid. My strategy was to add tiles with  `page-break-after: always;` on so the user can move the tiles to where the pagebreak is required.
 
However turns out the `position: absolute` breaks this since `position: relative` is required. Like here: https://stackoverflow.com/questions/20871535/how-to-force-page-break-between-absolutely-positioned-elements-in-css

Any ideas?

**Comment by hickeroar** [comment]
Nah I didn't have any luck getting it working while using the grid layout. I just ended up rendering the contents of the grid items independently

**Comment by sayo96** [comment]
Any update on this

**Comment by JellyWX** [comment]
With some tweaking, try this (SCSS):
```css
@media print {
.react-grid-item {
        position: unset !important;
        transform: unset !important;
        margin: 10px;
        display: inline-block;

        > div {
            page-break-inside: avoid;
            break-inside: avoid;
        }
    }

    .react-grid-layout {
        height: unset !important;
        display: table;
    }
}
```
