### ISSUE TITLE
size calculation is wrong when we hide the react-resizable-handle on not hovering on it.

### ISSUE THREAD

**Issue by john-hu** [STRML/react-grid-layout#611]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [x] Bug

If you have a question or bug report, please use the [WebpackBin Template] (http://www.webpackbin.com/EJF48h_rz) (I can't do that)
to demonstrate. It is much easier for us to help you if you do.

WebpackBin doesn't work now. I demo the issue at [Codesandbox](https://codesandbox.io/s/k13rlr34x5) https://codesandbox.io/s/k13rlr34x5

The code is cut from basic example.

Reproduce:
1. add the following css:

```css
.react-resizable-handle {
  display: none;
}

.react-grid-item:hover > .react-resizable-handle {
  display: block;
}
```
2. move mouse in any .react-grid-item element to see the resizable-handle
3. drag resizable-handle fast  ==>> size is wrong.

The demo video is made. Please find it at the following attachment. BTW, I cannot upload it as mp4, please download it and uncompress it.

[react-grid-layout-css-issue.mp4.zip](https://github.com/STRML/react-grid-layout/files/1241750/react-grid-layout-css-issue.mp4.zip)
