### ISSUE TITLE
How can I show the grid boxes or grid line?

### ISSUE THREAD

**Issue by wongjiahau** [STRML/react-grid-layout#658]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [X] Question
- [ ] Feature Request
- [ ] Bug

Is is possible to show the grid line or grid boxes for React-Grid-Layout?

**Comment by codepunkt** [comment]
Yes, it's possible. Just not out of the box.

**Comment by wongjiahau** [comment]
@codepunkt  Do you mind to provide me the code to achieve that?

**Comment by kutyepov** [comment]
This also can be achieved using css'
[background-image](https://www.w3schools.com/cssref/pr_background-image.asp)
[background-size](https://www.w3schools.com/csSref/css3_pr_background-size.asp)

**Comment by wongjiahau** [comment]
@kutyepov But is that consider a hack?

**Comment by kutyepov** [comment]
@wongjiahau nope

**Comment by wongjiahau** [comment]
@kutyepov Do you mind to demonstrate? I would like to know it

**Comment by jackie-benowitz** [comment]
Metabase does a good job of doing it [Metabase](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/dashboard/components/grid/GridLayout.jsx) that you can take *inspiration* from

**Comment by alphasen** [comment]
> [Metabase](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/dashboard/components/grid/GridLayout.jsx) does a good job of doing it that you can take _inspiration_ from

this is too complex，how about this
```css
.rgl-container{
    position: relative;
}
.rgl-bg{
    position: absolute;
    height: 100%;
    left: 10px;
    top: 0;
    right: 10px;
    background: linear-gradient(90deg, #f5f5f5 4.16666667%, transparent 4.16666667%, transparent 8.33333333%, #f5f5f5 8.33333333%, #f5f5f5 12.5%, transparent 12.5%, transparent 16.66666667%, #f5f5f5 16.66666667%, #f5f5f5 20.83333333%, transparent 20.83333333%, transparent 25%, #f5f5f5 25%, #f5f5f5 29.16666667%, transparent 29.16666667%, transparent 33.33333333%, #f5f5f5 33.33333333%, #f5f5f5 37.5%, transparent 37.5%, transparent 41.66666667%, #f5f5f5 41.66666667%, #f5f5f5 45.83333333%, transparent 45.83333333%, transparent 50%, #f5f5f5 50%, #f5f5f5 54.16666667%, transparent 54.16666667%, transparent 58.33333333%, #f5f5f5 58.33333333%, #f5f5f5 62.5%, transparent 62.5%, transparent 66.66666667%, #f5f5f5 66.66666667%, #f5f5f5 70.83333333%, transparent 70.83333333%, transparent 75%, #f5f5f5 75%, #f5f5f5 79.16666667%, transparent 79.16666667%, transparent 83.33333333%, #f5f5f5 83.33333333%, #f5f5f5 87.5%, transparent 87.5%, transparent 91.66666667%, #f5f5f5 91.66666667%, #f5f5f5 95.83333333%, transparent 95.83333333%);
}
```
```jsx
<div className="rgl-container">
                <div className="rgl-bg">
                    
                </div>
                <ReactGridLayout
                    {...this.props}
                    onLayoutChange={this.onLayoutChange}
                    onResize={this.onResize}
                >
                    {this.generateDOM()}
                </ReactGridLayout>
            </div>
```
